Remove storybook
MetaFam/TheGame pull request #1044
Opened 2022-01-14 14:09 UTC by firattale

Removing storybook from everywhere

2022-01-14 15:43 UTC, vidvidvid reviewed
`yarn.lock` changes are missing - did you run `yarn` after removing the packages?
Also the deployment is failing for some reason - @dysbulic could you take a look at what's happening, please?

2022-01-14 22:00 UTC, vidvidvid requested changes
A couple of more packages are left to uninstall - please double check they are not used anywhere else and throw them into the abyss.

2022-01-14 22:42 UTC, firattale commented on packages/design-system/.storybook/main.js
> -          loader: require.resolve('ts-loader'),
I removed them, thanks for noticing.

2022-01-15 09:25 UTC, vidvidvid commented on packages/design-system/.storybook/main.js
> -          loader: require.resolve('ts-loader'),
np, thanks for removing

2022-01-15 09:26 UTC, vidvidvid approved these changes

2022-01-15 09:26 UTC, vidvidvid commented
We can merge!

2022-01-15 12:23 UTC, merged