Quest roles
MetaFam/TheGame pull request #1075
Opened 2022-01-24 18:25 UTC by vidvidvid

## Overview

**What features/fixes does this PR include?**

Added `quest_roles` needed for #1034 
Added `basic` flag to determine which roles to display during onboarding and which to display when selecting roles for quests.

paired-with: @dan13ram

2022-01-24 20:20 UTC, vidvidvid commented
@dan13ram please confirm if i included everything i should have included in regards to BE changes in this pr :)

2022-01-25 15:38 UTC, dan13ram commented on packages/web/graphql/getQuests.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-expressions
@vidvidvid  This is not necessary in this PR but looks like it doesn't make a big difference.
But you may also wanna include changes in `packages/backend/src/handlers/actions/quests/createQuest/createQuest.ts` as well.

2022-01-25 15:51 UTC, dan13ram commented on packages/web/graphql/getQuests.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-expressions
also I'm not able to find changes related to `quest_completion` and `quest` table relationship that we discussed over chat. Would that be included in a future PR ?

2022-01-25 21:43 UTC, alalonde requested changes
can you consolidate the migrations? From what I can see there should only be 3. You can test them locally via `hasura migrate apply ...`

2022-01-26 08:58 UTC, vidvidvid commented
rebasing this branch onto develop and running `yarn update-schema` completely messes up the schema`.graphql`. any idea why is that happening? @dysbulic @dan13ram @alalonde ?

2022-01-26 09:29 UTC, dysbulic commented
> rebasing this branch onto develop and running `yarn update-schema` completely messes up the schema`.graphql`.

@vidvidvid, have you run `yarn && yarn docker:clean && docker-compose up --build` to rebuild the database? Your existing db might have migrations in it that are out of sync given the large number of migrations in #943.

When you say it messes up `schema.graphql`, what do you mean? What sorts of errors are you getting?

2022-01-26 10:24 UTC, vidvidvid commented
> @vidvidvid, have you run `yarn && yarn docker:clean && docker-compose up --build` to rebuild the database? Your existing db might have migrations in it that are out of sync given the large number of migrations in #943.

Not yet, I'll do that and let you know how it works.

> When you say it messes up `schema.graphql`, what do you mean? What sorts of errors are you getting?

It builds a completely different structure, as if it didn't take into the consideration all of your migrations.

2022-01-26 10:27 UTC, vidvidvid commented
@dysbulic `yarn && yarn docker:clean && docker-compose up --build` fails at `yarn`:

```
vidtopolovec@Vids-MBP TheGame % yarn
yarn install v1.19.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "typescript@4.5.4" is incompatible with requested version "typescript@^3.7.3"
warning Resolution field "typescript@4.5.4" is incompatible with requested version "typescript@^2.6.2"
warning Resolution field "typescript@4.5.4" is incompatible with requested version "typescript@^2.6.2"
success Already up-to-date.
$ lerna run prepare && husky install
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run prepare"
lerna ERR! yarn run prepare exited 1 in '@metafam/web'
lerna ERR! yarn run prepare stdout:
yarn run v1.19.0
$ yarn generate
$ graphql-codegen --config=codegen.yml
[11:25:29] Parse configuration [started]
[11:25:30] Parse configuration [completed]
[11:25:30] Generate outputs [started]
[11:25:30] Generate ./graphql/autogen/types.ts [started]
[11:25:30] Load GraphQL schemas [started]
[11:25:30] Load GraphQL schemas [failed]
[11:25:30] → Failed to load schema
[11:25:30] Generate ./graphql/autogen/types.ts [failed]
[11:25:30] → Failed to load schema
[11:25:30] Generate outputs [failed]
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run prepare stderr:
Something went wrong
error Command failed with exit code 1.
error Command failed with exit code 1.
lerna ERR! yarn run prepare exited 1 in '@metafam/web'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

2022-01-26 10:43 UTC, dysbulic commented
> Does `yarn generate` fail because the `schema.graphql` is not valid?

It is possible… Try running `yarn generate`. I added a `DEBUG=1` environment variable to that command that should cause it to print the file and line where it is failing.

2022-01-26 11:04 UTC, vidvidvid commented
@dysbulic I had a missing query in the schema, `yarn generate` worked after i added it 👍

2022-01-26 11:06 UTC, vidvidvid commented
> can you consolidate the migrations? From what I can see there should only be 3. You can test them locally via `hasura migrate apply ...`

Will look into it 👍

2022-01-30 18:24 UTC, vidvidvid commented
@alalonde I consolidated the migrations, but I'm not sure how to merge [this](https://github.com/MetaFam/TheGame/blob/ff49200507303c3ee113ad01e894a1501be4848e/hasura/migrations/1641640073308_create_table_public_quest_role/up.sql) and [that](https://github.com/MetaFam/TheGame/blob/ff49200507303c3ee113ad01e894a1501be4848e/hasura/migrations/1642342313101_alter_table_public_quest_role_drop_constraint_quest_role_quest_id_key/up.sql), could you help me out with that or could we perhaps just push this?

2022-02-01 18:27 UTC, alalonde reviewed
You can have multiple lines in a given migration, both up and down

2022-02-01 18:27 UTC, alalonde commented on hasura/metadata/actions.graphql
> +  roles_id : [uuid]!
let's make this camelcase for consistency

2022-02-01 18:27 UTC, alalonde commented on hasura/metadata/actions.graphql
> +  roles_id : [uuid]!
`roleIds` ?

2022-02-02 11:02 UTC, vidvidvid commented
@alalonde I changed `skills_id` -> `skillIds` and `rolesId` -> `roleIds`, tested creating and editing quests in the client PR and everything works fine! :)

2022-02-02 13:15 UTC, vidvidvid commented
> You can have multiple lines in a given migration, both up and down

@alalonde so should i join the quest role migrations?
`hasura/migrations/1641640073308_create_table_public_quest_role/up.sql`:
```
CREATE TABLE "public"."quest_role"("quest_id" UUID NOT NULL, "role" text NOT NULL, "rank" integer, PRIMARY KEY ("quest_id","role") , FOREIGN KEY ("quest_id") REFERENCES "public"."quest"("id") ON UPDATE restrict ON DELETE cascade, FOREIGN KEY ("role") REFERENCES "public"."PlayerRole"("role") ON UPDATE restrict ON DELETE restrict, UNIQUE ("quest_id"));
```

and `hasura/migrations/1642342313101_alter_table_public_quest_role_drop_constraint_quest_role_quest_id_key/up.sql`:

`alter table "public"."quest_role" drop constraint "quest_role_quest_id_key";`
by putting one below the other in the same file?

2022-02-02 15:43 UTC, alalonde commented
> > You can have multiple lines in a given migration, both up and down
> 
> @alalonde so should i join the quest role migrations? `hasura/migrations/1641640073308_create_table_public_quest_role/up.sql`:
> 
> ```
> CREATE TABLE "public"."quest_role"("quest_id" UUID NOT NULL, "role" text NOT NULL, "rank" integer, PRIMARY KEY ("quest_id","role") , FOREIGN KEY ("quest_id") REFERENCES "public"."quest"("id") ON UPDATE restrict ON DELETE cascade, FOREIGN KEY ("role") REFERENCES "public"."PlayerRole"("role") ON UPDATE restrict ON DELETE restrict, UNIQUE ("quest_id"));
> ```
> 
> and `hasura/migrations/1642342313101_alter_table_public_quest_role_drop_constraint_quest_role_quest_id_key/up.sql`:
> 
> `alter table "public"."quest_role" drop constraint "quest_role_quest_id_key";` by putting one below the other in the same file?

Just an FYI, no need this time :)

2022-02-02 15:44 UTC, alalonde approved these changes

2022-02-02 16:54 UTC, merged