Ensure that only known users can go through the guild setup process
MetaFam/TheGame pull request #1100
Opened 2022-02-01 20:20 UTC by alalonde

## Overview

**What features/fixes does this PR include?**

- Only known users (those with a connected profile) can go through the guild setup process. This enforces that. 
- Form visual improvements
- Added more detail to the "DAO address" field

Closes #1063 

## Implementation

**Side effects**

I made a CSS change to the shared `Field` component to make it less opinionated.

## Assets

<img width="757" alt="image" src="https://user-images.githubusercontent.com/1402582/152044868-d9058db6-08d5-4bd2-b252-b58a6781de68.png">

2022-02-01 21:48 UTC, vidvidvid commented
tested the workflow, looks good to me!
the only improvement suggestion would be to perhaps to add the button to connect inside the
> Please log in or create a player profile by pressing the "Connect"

but it's not required at all, since the continuation of this message is clear enough.

2022-02-03 19:42 UTC, dysbulic commented
> perhaps to add the button to connect inside the

You could link the “create a profile” text to [/me](//test.metagame.wtf/me). That will present them with a login prompt.

2022-02-03 19:54 UTC, dysbulic requested changes

2022-02-03 19:54 UTC, dysbulic commented on packages/web/components/Guild/GuildForm.tsx
> +          <span className="description">
I would use `chakra.span` or `<Text as="span">`, remove the class, and move the `Box`'s `sx` attribute down here.

Though, honestly, given how the elements are used on the page, you could use a `block` element, so just `<Text/>`.

2022-02-03 19:54 UTC, dysbulic commented on packages/web/components/Guild/GuildForm.tsx
> +          <span className="description">
If you want to repeat the style, create a local component like:

```typescript
const Description: React.FC = ({ children }) => (
  <Text as="span" ml={4} mt={1} fontSize="sm">
    {children}
  </Text>
);
```
```suggestion
          <Description>
```

2022-02-03 19:54 UTC, dysbulic commented on packages/web/components/Guild/GuildForm.tsx
> +              DaoHaus Supergraph
```suggestion
              DaoHaus Subgraph
```

2022-02-05 05:27 UTC, dan13ram commented on packages/web/components/Guild/GuildForm.tsx
> +              DaoHaus Supergraph
Its called Supergraph

2022-02-05 05:51 UTC, dan13ram approved these changes
LGTM

2022-02-05 16:12 UTC, dysbulic approved these changes

2022-02-05 20:47 UTC, merged