Onboarding Guidance Page
MetaFam/TheGame pull request #1499
Opened 2023-01-18 00:42 UTC by nitegeist

## Overview

**What features/fixes does this PR include?**
* Fixes background image layout issue
* Fixes widows in the card contents
* Fixes "I understand" button linking to the wrong place
* Fixes cards not being animated
* Adds up/down animation to pointer hand

**Please provide the GitHub issue number**

Closes #1495.

## Assets

Design: [Figma Design](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=4143%3A1628)

2023-01-18 02:00 UTC, dysbulic reviewed
I haven't visually inspected the site at all, this is purely a semantics & code standards review.

Maybe @luxumbra would be willing to give it a once over in the bowser.

2023-01-18 02:20 UTC, nitegeist commented on packages/web/components/Landing/OnboardingGuidance/index.tsx
> +      }}
Thanks for the shorthand!

2023-01-18 02:21 UTC, nitegeist commented on packages/web/components/Landing/OnboardingGuidance/index.tsx
> +            <UnorderedList pt={4} pl={4} fontWeight={300}>
The design uses light font weighht here instead of normal so I've changed this to light.

2023-01-18 02:21 UTC, nitegeist commented on packages/web/components/Landing/OnboardingGuidance/index.tsx
> +            <UnorderedList pt={4} pl={4} fontWeight={300}>
The design uses light font weighht here instead of normal so I've changed this to light

2023-01-19 20:23 UTC, alalonde requested changes
Reviewed the deployment, here's what I found:

- I think the link in #1 ("I understand") in the referenced ticket is still wrong.
- There is no padding or margin at the bottom of the page now, which looks weird

+1 for the added animations!

2023-01-19 21:10 UTC, nitegeist commented
> Reviewed the deployment, here's what I found:
> 
> - I think the link in #1 ("I understand") in the referenced ticket is still wrong.
> - There is no padding or margin at the bottom of the page now, which looks weird
> 
> +1 for the added animations!

Hey @alalonde where is the link for the "I understand" button supposed to go? The link provided to me goes to the profile setup page so that's what I've put there. As for the spacing at the bottom of the page, I'm working on a fix for that.

2023-01-20 17:08 UTC, alalonde commented
> Hey @alalonde where is the link for the "I understand" button supposed to go?
It says right in the issue, #1495.

2023-01-21 21:21 UTC, alalonde approved these changes
Looks good, thanks!

2023-01-21 21:22 UTC, merged