Feature/ens - ready for review
MetaFam/TheGame pull request #1524
Opened 2023-02-15 16:13 UTC by Seroxdesign

2023-02-15 16:14 UTC, Seroxdesign commented
Closes:

https://github.com/MetaFam/TheGame/pull/1513

2023-02-15 20:13 UTC, dysbulic commented
https://user-images.githubusercontent.com/181523/219142278-3738f0d3-88ed-41be-81ac-f8b26b4c811b.mp4

2023-02-15 22:54 UTC, Seroxdesign commented
> 

I added a check for username, this issue should be resolved now.

2023-02-16 18:38 UTC, alalonde commented
@Seroxdesign Could you please squash some of these commits? At least the testing ones (presumably that's what all the up/down.sql changes were)

2023-02-16 18:51 UTC, alalonde commented
I did a bit of testing, including finding players with ENS names and usernames and vice versa. Everything looks to be working from my minimal testing

2023-02-16 20:17 UTC, alalonde commented
> Could you please squash some of these commits?

Actually, disregard this, I didn't realize commits were squashed automatically on merge

2023-02-20 10:50 UTC, Seroxdesign commented
> > Could you please squash some of these commits?
> 
> Actually, disregard this, I didn't realize commits were squashed automatically on merge

I'm assuming this is no longer an issue, so I won't be squashing any commits.

2023-02-21 16:36 UTC, alalonde requested changes

2023-02-21 16:41 UTC, Seroxdesign commented on packages/design-system/vite.config.ts.timestamp-1675691765700.mjs
> +import react from "file:///home/sero/TheGame/node_modules/@vitejs/plugin-react/dist/index.mjs";
@alalonde this popped up while testing, will delete, not relevant to PR

2023-02-21 16:50 UTC, Seroxdesign commented on hasura/metadata/tables.yaml
> +      foreign_key_constraint_on: rank
Changes were reversed. all happened during testing @alalonde

2023-02-22 04:20 UTC, alalonde approved these changes

2023-02-23 20:13 UTC, closed without merging