Made a couple small tweaks to the ComposeDB profile model
MetaFam/TheGame pull request #1592
Opened 2023-08-11 03:53 UTC by alalonde

## Overview

Closes #1589

## Follow up Improvement Ideas

Once this gets merged, I'll need to deploy the model to our production node as well

2023-08-25 06:13 UTC, Seroxdesign approved these changes
Again not sure what this does, but LGTM

2023-08-30 04:35 UTC, dysbulic requested changes
These still don't look quite right to me. Also, can someone be colorless on the five-color disposition, so the `minLength` would be zero?

*(Sorry for taking so long. Clearing headspace to review properly has been a challenge.)*

2023-08-30 04:35 UTC, dysbulic commented on packages/utils/schema/user-profile.graphql
> +  emoji: String @string(maxLength: 3)
OpenMoji names their SVGs of emojis based on the characters. There's a `F9D1-1F3FB-200D-2764-FE0F-200D-1F48B-200D-1F9D1-1F3FF.svg`, *(a light skinned man loves a dark skinned woman)*, meaning there's at least series of ten.

There's no indication the Unicode people are going to tire of coming up with these strings, so why not do something like 20?

2023-08-30 04:35 UTC, dysbulic commented on packages/utils/schema/user-profile.graphql
> +  aspectRatio: Float @float(min: 0, max: 2)
It seems like the aspect ratio can be of arbitrary maximum size. Discord banners are 800:320 which is 2.5.

2023-09-20 16:00 UTC, alalonde commented
> These still don't look quite right to me. Also, can someone be colorless on the five-color disposition, so the `minLength` would be zero?

I removed the `minLength` requirement

2023-09-20 17:00 UTC, dysbulic approved these changes
LGTM.

2023-09-20 17:00 UTC, merged