Unify signup - READY FOR REVIEW #5
MetaFam/TheGame pull request #1608
Opened 2023-09-20 16:12 UTC by nitegeist

## Overview

**What features/fixes does this PR include?**
This PR creates a page that unifies the signup of players, guilds and patrons
**Please provide the GitHub issue number**

Closes #

https://www.notion.so/meta-game/Improving-UX-02ea24e2fdc14cc4be0bebbede3b9487?p=e7842eac487f4e11b3495363133f09a2&pm=s

https://www.notion.so/meta-game/Rotating-1liners-4ab98ad7d7ab4821a8cfff7b0ec94c14

## Follow up Improvement Ideas

- [ ] please list any improvement/ideas

## Implementation

**Describe technical (nontrivial / non-obvious) parts of your code**

**Side effects**

## Assets

[Include screenshots/videos if it makes reviewing easier.]

2023-10-11 13:24 UTC, Seroxdesign requested changes

2023-10-13 09:11 UTC, Seroxdesign commented
@nitegeist left you some comments in the discord channel, there's some visual issues that need to be tended to.

2023-10-23 01:41 UTC, alalonde commented
Please reference an issue / artifact so I can test / review

2023-10-23 14:49 UTC, nitegeist commented
> Please reference an issue / artifact so I can test / review

I'll have to make one. I don't think it exists

2023-10-24 13:19 UTC, Seroxdesign commented
> Please reference an issue / artifact so I can test / review

https://www.notion.so/meta-game/Improving-UX-02ea24e2fdc14cc4be0bebbede3b9487?p=e7842eac487f4e11b3495363133f09a2&pm=s

2023-10-24 17:45 UTC, alalonde requested changes
Each tab should have its own URL so as not to break navigation and allow linking

2023-10-24 17:48 UTC, alalonde commented
Is this really what we want it to look like? 
<img width="1483" alt="image" src="https://github.com/MetaFam/TheGame/assets/1402582/2b06a131-643d-4842-829c-dbb09499dac1">

@davort @peth-yursick Can you take a look at this and suggest improvements? https://frontend-pr-1608-mjhnbmqqna-uk.a.run.app/onboarding

2023-10-26 03:53 UTC, nitegeist commented
> Each tab should have its own URL so as not to break navigation and allow linking

This has been added with the latest commit

2023-10-27 01:21 UTC, alalonde commented
> Each tab should have its own URL so as not to break navigation and allow linking

Close; when you land on /signup, it should redirect to /signup?tab=player

You can test by navigating back and forward, it should not skip any navigations

2023-10-27 04:28 UTC, nitegeist commented
> when you land on /signup, it should redirect to /signup?tab=player

Done in the latest commit

2023-11-01 18:46 UTC, peth-yursick commented
getting "service unavailable" on both this & test.metagame

2023-11-02 14:52 UTC, Seroxdesign requested changes

2023-11-08 04:46 UTC, nitegeist commented on packages/web/components/Landing/Signup/index.tsx
> +  useEffect(() => {
Removed the useEffect.

2023-11-08 04:46 UTC, nitegeist commented on packages/web/lib/hooks/useActiveTab.ts
> +export default function useActiveTab() {
This hook is used for quite a bit of things other than simply setting player as default active tab.

2023-11-08 04:47 UTC, nitegeist commented on packages/web/components/Landing/Signup/index.tsx
> +  );
Done.

2023-11-10 12:27 UTC, Seroxdesign commented
@nitegeist 

![image](https://github.com/MetaFam/TheGame/assets/69639595/d0cc5fec-084f-4d43-9479-280d17c88feb)

2023-11-17 11:27 UTC, Seroxdesign approved these changes

2023-11-19 05:41 UTC, alalonde approved these changes

2023-11-19 05:41 UTC, merged