Wip re-design of playbooks
MetaFam/TheGame pull request #1652
Opened 2023-12-04 14:13 UTC by vidvidvid

https://www.figma.com/file/IzgwXeC5eDVo7ayAmYihwS/Combine-Paths?node-id=268%3A2477&mode=dev

2023-12-08 11:09 UTC, peth-yursick commented
I can't see if the design was applied to all 3, so thought I should point that out just in case - since "paths", "playbooks" & "great houses" are all "academy" now - this design should apply to all 3.


Also reminds me of the links:

While doing that, might also make sense to move them together.
Right now we got:
Playbooks - metagame.wtf/learn/playbooks/meme-driven-organizations
Great houses - metagame.wtf/learn/great-houses/house-of-ethereum
Paths - metagame.wtf/play/paths/engaged-octos-path

Should all be:
Playbooks - metagame.wtf/academy/meme-driven-organizations
Great houses - metagame.wtf/academy/house-of-ethereum
Paths - metagame.wtf/academy/engaged-octos-path

In short, all of these:
/learn/playbooks/
/learn/great-houses/
/play/paths/
Should be replaced with just: /academy/

Depending on how much additional work this requires, we can make it into a new issue, up to you.

2023-12-10 12:30 UTC, peth-yursick commented
Alright, to recap:
[ ] mobile, guess you knew that but just in case
[ ] submit button button not the same color as connect & other buttons
[ ] top slot in the sidebar has rounded corners, should be straight like others
[ ] need to apply this design to paths & great houses as well
[ ] (optional) move playbooks, great houses & paths from /learn/playbooks/, /learn/great-houses/ & /play/paths/ to just: /academy/
[ ] (this would also fix the paths being broken)
[ ] currently, the top item on the sidebar has round corners & all others have straight. The topmost should have round top corners & bottomost should have round bottom corners, others are straight

2024-01-01 10:23 UTC, Seroxdesign requested changes

2024-01-01 10:23 UTC, Seroxdesign commented on packages/web/components/QuestChain/UploadProof.tsx
> +                description: `Wrong Chain, please switch to ${
You're handling 3 separate cases and the description only covers 1, maybe change the description to something like: "Please ensure your wallet is connected to the x chain."

2024-01-02 11:39 UTC, Seroxdesign approved these changes

2024-01-08 13:54 UTC, merged