Fixed an issue doesn't show save map title in change popover modal
MetaFam/TheGame pull request #359
Opened 2021-02-19 15:20 UTC by ace-smart

Fixes  #358

2021-03-01 07:49 UTC, pakokrew approved these changes

2021-03-01 07:49 UTC, pakokrew commented on packages/metamaps/pages/[author_address]/map/[id].tsx
> +  dispatch({ type: 'POPOVER_NAME_INPUT', value: data?.Map_by_pk.name });
People working on this project should learn about render mechanisms of React and how works hooks.

The content of this method, from line 18 to line 88, is executed at each render. 
It means that:
- the dispatches will be sent many times
- the items will be computed many times

You must wrap this logic into respectively useEffect and useMemo

2021-04-21 16:27 UTC, alalonde requested changes
Please change to leverage `useEffect` and `useMemo` appropriately, and rebase from master.

2021-05-01 07:27 UTC, dan13ram commented
No longer necessary as we have deprecated `metamaps`

2021-06-09 14:42 UTC, dan13ram commented
Closing this since we are no longer working on `metamaps`. Please reopen if needed in the future.

2021-06-09 14:42 UTC, closed without merging