setup basic brightId hook
MetaFam/TheGame pull request #361
Opened 2021-02-22 16:49 UTC by dan13ram

2021-03-01 08:00 UTC, pakokrew requested changes
I don't understand how you plan to store brightid verification in the backend.
I believe what you did in the frontend trustlessly works, but I don't see what will change the information in the backend.

What we did before for github and twitter, is that the backend will check for the verifications (from 3box for these, in `updateBoxProfile` action), and then add PlayerAccount roles with the corresponding informations. Then the frontend just reads the player=>accounts values to know the verified accounts. 

Would you mind using the same logic, make the backend actions verify brightid in addition to 3box, and add a row in Player_Account ?

2021-03-01 08:03 UTC, dan13ram commented on packages/web/graphql/mutations/updateBrightIDStatus.ts
> +  mutation UpdatePlayerBrightIDVerified($verified: Boolean!) {
this is changing completely and won't be necessary

2021-03-01 08:04 UTC, dan13ram commented
> I don't understand how you plan to store brightid verification in the backend.
> I believe what you did in the frontend trustlessly works, but I don't see what will change the information in the backend.
> 
> What we did before for github and twitter, is that the backend will check for the verifications (from 3box for these, in `updateBoxProfile` action), and then add PlayerAccount roles with the corresponding informations. Then the frontend just reads the player=>accounts values to know the verified accounts.
> 
> Would you mind using the same logic, make the backend actions verify brightid in addition to 3box, and add a row in Player_Account ?

please check https://github.com/MetaFam/TheGame/pull/362. I've updated the logic completelt

2021-03-01 08:06 UTC, dan13ram commented on packages/web/graphql/mutations/updateBrightIDStatus.ts
> +  mutation UpdatePlayerBrightIDVerified($verified: Boolean!) {
as mentioned in the labels this is a WIP. I'll change the logic and update this PR today. Thanks for taking a look! :)

2021-03-01 08:07 UTC, pakokrew commented
> please check #362. I've updated the logic completely

My bad, didn't see the WIP label 🤦‍♂️ ...
So you will not store anything in the backend anymore ?

2021-03-01 08:11 UTC, dan13ram commented
> > please check #362. I've updated the logic completely
> 
> My bad, didn't see the WIP label  ...
> So you will not store anything in the backend anymore ?

Yeah as you can see in the other PR #362 I've added a remote schema relationship which queries BrightID apis to check for status, which is stored against the player => `brightid_status`.
This will be used by the frontend to display verified status.

In case a player is not verified, then we shall show a QR for the user to scan using their brightID app and verify.

Then the user must **refresh** the page for the status to get updated. 

Please let me know if there can be a better implementation here!

2021-03-01 08:15 UTC, pakokrew commented
> > > please check #362. I've updated the logic completely
> > 
> > 
> > My bad, didn't see the WIP label  ...
> > So you will not store anything in the backend anymore ?
> 
> Yeah as you can see in the other PR #362 I've added a remote schema relationship which queries BrightID apis to check for status, which is stored against the player => `brightid_status`.
> This will be used by the frontend to display verified status.
> 
> In case a player is not verified, then we shall show a QR for the user to scan using their brightID app and verify.
> 
> Then the user must **refresh** the page for the status to get updated.
> 
> Please let me know if there can be a better implementation here!

I believe that's good, the only issue I see here is that hasura will have to fetch brightid endpont each time we fetch user data, which can be slow. 
We were thinking about having some caching for remote schema but that's not for today.
About having to refresh, can't nextjs allow us to invalidate the initial props and fetch them again?

2021-03-01 08:18 UTC, dan13ram commented
> I believe that's good, the only issue I see here is that hasura will have to fetch brightid endpont each time we fetch user data, which can be slow.
> We were thinking about having some caching for remote schema but that's not for today.

Sounds good. We can then look at that as a separate issue

> About having to refresh, can't nextjs allow us to invalidate the initial props and fetch them again?

Yes its possible to do that. But will require an action from the user. Do you think we can have a refresh button somewhere on the profile for re-fetching user's data?

2021-03-01 08:20 UTC, pakokrew commented
> > I believe that's good, the only issue I see here is that hasura will have to fetch brightid endpont each time we fetch user data, which can be slow.
> > We were thinking about having some caching for remote schema but that's not for today.
> 
> Sounds good. We can then look at that as a separate issue
> 
> > About having to refresh, can't nextjs allow us to invalidate the initial props and fetch them again?
> 
> Yes its possible to do that. But will require an action from the user. Do you think we can have a refresh button somewhere on the profile for re-fetching user's data?

Maybe while the modal with the QRCode is open we can poll brightID to see if the profile have been validated, if yes, re-fetch.

2021-03-01 08:25 UTC, dan13ram commented
> Maybe while the modal with the QRCode is open we can poll brightID to see if the profile have been validated, if yes, re-fetch.
My bad. It is possible to refetch only for queries made on the frontend. The /player/[username] pages are statically generated on the backend. And there isn't a way currently to re-generate them from the frontend. It just automatically gets updated every 1 sec. 
See https://github.com/MetaFam/TheGame/blob/b0ab6f1e2d072f9a4746ca2124e8cee1a67edca0/packages/web/pages/player/%5Busername%5D.tsx#L190

2021-03-01 10:41 UTC, dan13ram commented on packages/web/components/Player/PlayerTile.tsx
> +              {verified && (
this line is the only change in this file along with useBrightIdStatus hook.

2021-03-02 05:21 UTC, pakokrew approved these changes
Minor changes (especially `useMemo` !) but LGTM

2021-03-02 05:21 UTC, pakokrew commented on packages/web/lib/hooks/brightId.ts
> +  const verified =
Maybe you can wrap these 3 variables in an object that you compute with `useMemo` then return.

2021-03-02 05:21 UTC, pakokrew commented on packages/web/lib/hooks/brightId.ts
> +        const isVerified =
Maybe factorize this logic of computing `verified` that is used two times in this file (l.20)

2021-03-02 05:21 UTC, pakokrew commented on packages/web/config.ts
> +    process.env.NEXT_BRIGHTID_APP_URL || 'https://app.brightid.org',
add to .env.sample

2021-03-02 05:21 UTC, pakokrew commented on packages/backend/src/config.ts
> +    process.env.NEXT_BRIGHTID_APP_URL,
add to .env.sample

2021-03-02 12:20 UTC, merged