Make the whole Player card clickable
MetaFam/TheGame pull request #383
Opened 2021-03-05 16:00 UTC by mquellhorst

Tried to fix #343 
Works fine on Brave

2021-03-05 18:57 UTC, dysbulic requested changes
¿You just moved the link to the top of the tree, right?

It shows a ton of lines changed b/c of spacing, but it looks like everything is in the same places.

You do need to put the `.env.sample` back.

2021-03-06 23:46 UTC, mquellhorst reviewed
Correct and added text-decoration none so not all the text get underlined on hover

2021-03-06 23:46 UTC, mquellhorst commented on .env.sample
> -COMPOSE_PROJECT_NAME=the-game
Yeah I did and thought I put it back before commiting.
Add the file the file again and recommit?

2021-03-07 16:41 UTC, dysbulic commented
This overrides the Twitter, Github and Etherscan links in the footer of the card even though the correct link address shows at the base of the browser.

I don't know how to fix this. z-index, maybe? Probably not.

Also the text in the profile is now cyan and not white.

2021-03-07 16:59 UTC, dysbulic commented
Apparently links within links is not a simple thing to address at all: https://stackoverflow.com/a/46707009

Unless you want to try to get this CSS-based example to work, this should probably go back to the issue, #343, for further discussion.

2021-03-07 20:18 UTC, mquellhorst commented
I'll look into it whether I can fix this, thanks!

2021-03-07 20:18 UTC, closed without merging