Feature/mega menu alt
MetaFam/TheGame pull request #758
Opened 2021-08-16 18:03 UTC by blake-hunsicker

This PR contains the UI for the MegaMenu, but does not include search functionality or a working wallet connect. It is meant to be responsive and render well on all devices.

The MegaMenu file is in [/components/MegaMenu.tsx](https://github.com/MetaFam/TheGame/blob/feature/mega-menu-alt/packages/web/components/MegaMenu.tsx), and contains the UI for the new navbar.

The text and links for the nav bar are sourced from [utils/menuLinks.ts](https://github.com/MetaFam/TheGame/blob/feature/mega-menu-alt/packages/web/utils/menuLinks.ts).

2021-08-16 22:39 UTC, mquellhorst commented
He @blake-hunsicker, nice work!

Some points:
The links should point to the following:
- Guilds -> my.metagame.wtf/guilds
- Guests -> my.metagame.wtf/quests

I would suggest placing a link to the balancer pool for planting seeds on the invest tab

I'll label the PR as WIP so you can finish it :)

2021-08-28 14:44 UTC, phys3 commented
> ![image](https://user-images.githubusercontent.com/7143583/131156342-4128d8f9-860d-4d1d-ae3f-ca1867aa79d3.png)
> The color of the menu items doesn't match the theme, and the height of the menu is too large

@hammadj i'll finish up this pr, do we have the design of the dropdowns for the mobile and desktop menu. i got access only for this https://www.figma.com/file/LAuXF0evRNBFv5djYlZUCi/Playbooks?node-id=1091%3A194960 which doesn't contain the expanded dropdowns

2021-09-05 11:26 UTC, dysbulic reviewed
Lots of little capitalization and redundancy things, but the basic logic looks solid.

I'd like to see fewer `px` values, but that's too big a pain to go back and fix.

2021-09-05 11:26 UTC, dysbulic commented on packages/web/utils/menuLinks.ts
> +          'Find out all about the Seeds; why, where & how you should buy them',
```suggestion
          'Find out all about the SEEDs; why, where & how you should buy them',
```

I think the currency name is all caps, whether or not we're doing that here I don't know…

2021-09-05 11:26 UTC, dysbulic commented on packages/web/utils/menuLinks.ts
> +        explainerText: 'Plant your Seeds and watch them grow',
```suggestion
        explainerText: 'Plant your SEEDs and watch them grow',
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/utils/menuLinks.ts
> +  menuItems?: any;
```suggestion
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/utils/menuLinks.ts
> +  icon?: any;
```suggestion
  icon?: string;
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/utils/menuLinks.ts
> +export interface MenuLink {
This interface is off. It nearly describes the nested objects, but is missing a couple fields. It is used as the type for the `MenuSectionLinks` which should just be something like:

```typescript
export interface MenuLinkSet {
  label: string;
  menuItems: MenuLink[];
}
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +    {MenuSectionLinks.map((section: any) => (
```suggestion
    {MenuSectionLinks.map((section: MenuLinkSet) => (
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +                  {section.menuItems.map((item: any) => (
```suggestion
                  {section.menuItems.map((item: MenuLink) => (
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +                      icon={item.icon}
```suggestion
                      {{ ...item }}
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +                  {section.menuItems.map((item: any) => (
```suggestion
                  {section.menuItems.map((item: MenuLink) => (
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +                      icon={item.icon}
```suggestion
                      {{ ...item }}
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +    mb="auto"
```suggestion
    my="auto"
    mr="0"
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +      pl={4}
```suggestion
      px={4} py={2}
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +      <Image src={XPStar} alt="XP" height={14} width={14} />{' '}
```suggestion
      <Image src={XPStar} alt="XP" height={14} width={14} mr={3}/>
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +      pl={4}
```suggestion
      px={4} py={2}
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +      <Image src={SeedMarket} alt="Seed" height={14} width={14} />{' '}
```suggestion
      <Image src={SeedMarket} alt="Seed" height={14} width={14} mr={3}/>
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +        name="alt text"
```suggestion
        name={getPlayerName(player)}
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +        height="52px"
```suggestion
        w="52px" h="52px"
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +        pr={4}
```suggestion
        px={4} py={1.5}
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +          mb="auto"
```suggestion
          my="auto"
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +              <PlayerStats player={user.player} pSeedBalance={pSeedBalance} />
```suggestion
              <PlayerStats player={user.player} {...{ pSeedBalance }} />
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +                Connect wallet
```suggestion
                Connect Wallet
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +                {section.menuItems.map((item: any) => (
```suggestion
                {section.menuItems.map((item: MenuLink) => (
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +                    p="12px 16px"
```suggestion
                    px={4} py={3}
```

2021-09-05 11:26 UTC, dysbulic commented on packages/web/components/MegaMenu.tsx
> +                      height="24px"
```suggestion
                      w="24px" h="24px"
```

2021-09-05 11:37 UTC, dysbulic commented on packages/web/utils/menuLinks.ts
> +export const MenuSectionLinks: MenuLink[] = [
```suggestion
export const MenuSectionLinks: MenuLinkSet[] = [
```

2021-09-05 12:22 UTC, mquellhorst commented
A couple of things about UX.
Originally the menu scrolls away with the content and on the players page the filters stick to the top of the page. \
Currently the menu sticks to the top of the page which results in the filters ending up behind the menu.
To solve this pls make the menu scroll up with the page

The Connect button is extremely large like this. I'ld prefer a regular button aligned in the center vertically.

2021-09-05 12:23 UTC, mquellhorst requested changes
A couple of things about UX.
Originally the menu scrolls away with the content and on the players page the filters stick to the top of the page.
Currently the menu sticks to the top of the page which results in the filters ending up behind the menu.
To solve this pls make the menu scroll up with the page

The Connect button is extremely large like this. I'ld prefer a regular button aligned in the center vertically.

2021-09-05 19:51 UTC, mquellhorst commented
Thanks for the quick update!
I see a couple more things tho. Hopefully you can fix these then it looks mergable :)

1. On desktop it seems the menu is no longer in te center of the navbar.
2. On mobile the opacity of the background is lower than 1 making the links a bit hard to read.
3. The menu overlaps the Connect button on mobile.
4. On mobile you can scroll the menu but you can keep scrolling through the whole page.

Could you center it on desktop.
Make the opacity 1 on mobile and make it don't overlap the connect button and only being able to scroll the menu so the menu sticks

Hope this is clear enough else just dm me :)
Again, thanks for your work!

2021-09-05 19:54 UTC, mquellhorst requested changes
Thanks for the quick update!
I see a couple more things tho. Hopefully you can fix these then it looks mergable :)

    On desktop it seems the menu is no longer in te center of the navbar.
    On mobile the opacity of the background is lower than 1 making the links a bit hard to read.
    The menu overlaps the Connect button on mobile.
    On mobile you can scroll the menu but you can keep scrolling through the whole page.

Could you center it on desktop.
Make the opacity 1 on mobile and make it don't overlap the connect button and only being able to scroll the menu so the menu sticks

Hope this is clear enough else just dm me :)
Again, thanks for your work!

2021-09-08 18:32 UTC, mquellhorst approved these changes
Looks good, thanks!!

2021-09-08 18:33 UTC, merged

2021-09-08 18:37 UTC, mquellhorst commented
Closes  #641