switch to MetaLink for edit profile
MetaFam/TheGame pull request #817
Opened 2021-09-11 08:35 UTC by phys3

2021-09-14 13:05 UTC, mquellhorst requested changes

2021-09-14 13:05 UTC, mquellhorst commented on packages/web/components/MegaMenu.tsx
>          {pSeedBalance || 0}
Currently the pSeedBalance is shown in 18 decimals
There is a helper in `@metafam/utils` called `numbers` which contains `amountToDecimal` to turn it in a readable number
It's also being used in 'web/utils/questHelper.ts' on line 31
Could you use it here?

2021-09-14 13:05 UTC, mquellhorst commented on packages/web/components/PlayerStatsBar.tsx
> +                </MetaLink>
Please add to link to edit the profile as well

2021-09-14 21:08 UTC, alalonde commented on packages/web/components/MegaMenu.tsx
> +  disconnect,
Why not just use the hooks directly rather than requiring them as props?

2021-09-15 13:11 UTC, mquellhorst requested changes

2021-09-15 13:11 UTC, mquellhorst commented on packages/web/components/MegaMenu.tsx
> +                  {...{ pSeedBalance, disconnect }}
You use the hooks in PlayerStats to retrieve them right?

2021-09-15 14:01 UTC, mquellhorst approved these changes
Closes #812 
Closes #819

2021-09-15 14:01 UTC, merged