feature: Dashboard section for Seed done for mvp.
MetaFam/TheGame pull request #900
Opened 2021-11-04 03:30 UTC by luxumbra

Adds CoinGecko API to handle the token data & React Vis library for adding charts in SVG. 

I also added maxH on the grid for the the seed & xp sections as under 2 rows high, they aren't ideal.

2021-11-18 21:16 UTC, mquellhorst requested changes

2021-11-18 21:16 UTC, mquellhorst commented on packages/web/components/Dashboard/Seed.tsx
> +    if (typeof token !== 'undefined') return;
Prob cleaner to set token null by default and check whether it's not null here

2021-11-18 21:16 UTC, mquellhorst commented on packages/web/components/Dashboard/Seed.tsx
> +    const plots: Array<string | any | AreaSeriesPoint> = [];
String and any should be removed here

2021-11-18 21:16 UTC, mquellhorst commented on packages/web/components/Dashboard/Seed.tsx
> +          onClick={() => toggleScale()}
just putting toggleScale between the curly braces should be enough

2021-11-18 21:16 UTC, mquellhorst commented on packages/web/components/Dashboard/Seed.tsx
> +        sx={{
I guess it would clean things up a bit more if you'ld put these styles in a const somewhere and just put the const here

2021-11-18 21:16 UTC, mquellhorst commented on packages/web/components/Dashboard/Seed.tsx
> +        return () => {};
doesn't need a return actually

2021-11-18 21:16 UTC, mquellhorst commented on packages/web/components/Dashboard/Seed.tsx
> +          return null;
just return is enough I think no null needed

2021-11-18 21:16 UTC, mquellhorst commented on packages/web/components/Dashboard/Seed.tsx
> +            ticker: ticker(tickers, 'balancer_v1'),
I'ld move all these function to the top assign the values to const and construct the json object

2021-11-18 21:16 UTC, mquellhorst commented on packages/web/components/Dashboard/Seed.tsx
> +        const buildTokenData = () => {
you can just take everything out of the function and pass the json object to setToken

2021-11-24 22:45 UTC, alalonde approved these changes
Nice! Looks good overall. Some comments:

1. The coingecko logo (for me) is hard-enough-to-see that it's like it's not there. Not sure what they dictate in their Terms of Service, but something like "Powered by CoinGecko" in an (i) Icon or something might look better.
2. React-spring looks pretty snazzy but, to your point, seems overweight. I think it's probably fine to leave in there for the being, assuming next.js / webpack does sufficient tree-shaking or other optimizations to thin it down.
3. Chart animation looks great! My only nitpick is the fade from white / purple / back to white on the xxD text looks a bit odd.

2021-11-26 20:56 UTC, alalonde commented
@mquellhorst Have your suggestions / comments been addressed? Would like to move this one through as it's a prerequisite for a bunch of other stuff

2021-11-30 02:50 UTC, alalonde approved these changes

2021-11-30 02:50 UTC, merged

2021-11-30 11:52 UTC, luxumbra commented
Thanks for the Merge @alalonde 🙏🏻